### ISSUE TITLE
Log an error object along with context-specific error message

### ISSUE THREAD

**Issue by raine** [ianstormtaylor/heroku-logger#15]
Hello,

Thanks for a great library.

I want to log an error object along with a message that describes the context of the error.

```js
log.error('Error while doing x', err)
```

However, that results in

```
[error] Error while doing x
``` 

I'm aware you can do `log.error(err)`, which results in a nice log message of the error, but most of time I actually want to include a custom message, without logging two lines.

What if `log.error('Error while doing x', err)` printed the following?

```
[error]: Error while doing x error="[object Object]" stack="TypeError: Cannot read prope
rty 'length' of null
    at redis.mgetAsync.then.then
message="Cannot read property 'length' of null"
```

**Comment by ianstormtaylor** [comment]
Sounds great to me!

**Comment by raine** [comment]
How do you feel about this?

```js
try {
  JSON.parse('#')
} catch (err) {
  log.error('failed to parse json', err)
}
```

```
[error] failed to parse json message="Unexpected token # in JSON at position 0" stack="SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
```

If this makes sense to you, I'll open a PR.

---

Another example that shows how extra properties of `Error` are merged to data as well.

```js
log.error('failed to update podcast', err)
```

```
error] failed to update podcast message="column \"sumary\" of relation \"podcast\" does not exist" stack="error: column \"sumary\" of relation \"podcast\" does not exist
   at Connection.parseE (/node_modules/pg/lib/connection.js:602:11)
   at Connection.parseMessage (/node_modules/pg/lib/connection.js:399:19)
   at Socket.<anonymous> (/node_modules/pg/lib/connection.js:121:22)
   at Socket.emit (events.js:189:13)
   at Socket.EventEmitter.emit (domain.js:441:20)
   at addChunk (_stream_readable.js:284:12)
   at readableAddChunk (_stream_readable.js:265:11)
   at Socket.Readable.push (_stream_readable.js:220:10)
   at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)" name=error length=128 severity=ERROR code=42703 detail= hint= position=40 internalPosition= internalQuery= where= schema= table= column= dataType= constraint= file=analyze.c line=2346 routine=transformUpdateTargetList

```

**Comment by ianstormtaylor** [comment]
@raine sounds good to me! As close as possible to the existing `log.error(e)` behavior but with the updated message would be good.
